/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    stacks: Stack;
    projects: Project;
    services: Service;
    experiences: Experience;
    messages: Message;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    stacks: StacksSelect<false> | StacksSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    site: Site;
    cinematic: Cinematic;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    cinematic: CinematicSelect<false> | CinematicSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrit l’image pour les lecteurs d’écran (obligatoire pour les images).
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stacks".
 */
export interface Stack {
  id: number;
  name: string;
  /**
   * Généré depuis le nom si vide.
   */
  slug?: string | null;
  category: 'language' | 'frontend' | 'backend' | 'architecture' | 'testing' | 'devops' | 'security' | 'ai';
  /**
   * Tape un slug Simple Icons (ex. docker, react — voir simpleicons.org) ou uploade un SVG. Sans icône, un monogramme est affiché.
   */
  icon?: {
    simpleIconSlug?: string | null;
    upload?: (number | null) | Media;
  };
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Généré depuis le titre si vide. Change-le avec précaution : il sert d’URL.
   */
  slug?: string | null;
  /**
   * Une phrase — affichée sur la carte.
   */
  tagline?: string | null;
  summary?: string | null;
  caseStudy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  stacks?: (number | Stack)[] | null;
  links?: {
    live?: string | null;
    repo?: string | null;
    caseStudyUrl?: string | null;
  };
  year?: number | null;
  client?: string | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: string;
  icon:
    | 'layers'
    | 'blocks'
    | 'bot'
    | 'cloud'
    | 'shield-check'
    | 'code'
    | 'database'
    | 'rocket'
    | 'cpu'
    | 'workflow'
    | 'globe'
    | 'smartphone';
  tint: 'amber' | 'violet' | 'blue' | 'teal';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  kind: 'work' | 'education';
  role: string;
  organization: string;
  location?: string | null;
  start: string;
  /**
   * Vide = en cours.
   */
  end?: string | null;
  summary?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stacks?: (number | Stack)[] | null;
  /**
   * Plus petit = plus haut dans la timeline.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  name: string;
  email: string;
  topic: 'project' | 'ai' | 'job' | 'other';
  message: string;
  ipHash?: string | null;
  locale?: ('fr' | 'en') | null;
  status?: ('new' | 'read' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'stacks';
        value: number | Stack;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stacks_select".
 */
export interface StacksSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  icon?:
    | T
    | {
        simpleIconSlug?: T;
        upload?: T;
      };
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  summary?: T;
  caseStudy?: T;
  cover?: T;
  gallery?: T;
  stacks?: T;
  links?:
    | T
    | {
        live?: T;
        repo?: T;
        caseStudyUrl?: T;
      };
  year?: T;
  client?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  tint?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  kind?: T;
  role?: T;
  organization?: T;
  location?: T;
  start?: T;
  end?: T;
  summary?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stacks?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  topic?: T;
  message?: T;
  ipHash?: T;
  locale?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  identity: {
    name: string;
    jobTitle: string;
    tagline?: string | null;
    location?: string | null;
  };
  hero?: {
    eyebrow?: string | null;
    rotatingTitles?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaPrimary?: string | null;
    ctaSecondary?: string | null;
    chips?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    trustedByTitle?: string | null;
    trustedBy?:
      | {
          name: string;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  about?: {
    headline?: string | null;
    bio?: string | null;
    /**
     * Calcule automatiquement années d’expérience, technologies et projets. Décoche pour saisir tes propres chiffres.
     */
    autoStats?: boolean | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  process?: {
    headline?: string | null;
    steps?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    /**
     * Affiche le téléphone publiquement. Désactivé par défaut (spam).
     */
    showPhone?: boolean | null;
    linkedin?: string | null;
    github?: string | null;
    /**
     * Destinataire des notifications du formulaire (jamais affiché publiquement).
     */
    contactTo?: string | null;
  };
  cv?: {
    cvFullstack?: (number | null) | Media;
    cvAi?: (number | null) | Media;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Avatar 3D et vidéos du hero. Tous les slots sont optionnels : le site a un repli pour chacun.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cinematic".
 */
export interface Cinematic {
  id: number;
  /**
   * Avatar 3D (.glb compressé meshopt, ≤ 3 Mo).
   */
  avatarModel?: (number | null) | Media;
  /**
   * Portrait de l’avatar (PNG/WebP transparent, ≤ 150 Ko) — repli si pas de 3D.
   */
  avatarPortrait?: (number | null) | Media;
  /**
   * Poster du hero (WebP/AVIF ≤ 150 Ko) — première image affichée (LCP).
   */
  heroPoster?: (number | null) | Media;
  /**
   * Vidéo d’intro 16:9 (≤ 4 Mo).
   */
  heroVideoDesktop?: {
    /**
     * Fichier .mp4 (H.264).
     */
    mp4?: (number | null) | Media;
    /**
     * Fichier .webm (VP9) — optionnel.
     */
    webm?: (number | null) | Media;
  };
  /**
   * Vidéo d’intro 9:16 (≤ 2 Mo).
   */
  heroVideoMobile?: {
    /**
     * Fichier .mp4 (H.264).
     */
    mp4?: (number | null) | Media;
    /**
     * Fichier .webm (VP9) — optionnel.
     */
    webm?: (number | null) | Media;
  };
  /**
   * Vidéo de transition « all-intra » scrubée au scroll (≤ 6 Mo).
   */
  scrubVideo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  identity?:
    | T
    | {
        name?: T;
        jobTitle?: T;
        tagline?: T;
        location?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        rotatingTitles?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaPrimary?: T;
        ctaSecondary?: T;
        chips?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        trustedByTitle?: T;
        trustedBy?:
          | T
          | {
              name?: T;
              url?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        headline?: T;
        bio?: T;
        autoStats?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        headline?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        showPhone?: T;
        linkedin?: T;
        github?: T;
        contactTo?: T;
      };
  cv?:
    | T
    | {
        cvFullstack?: T;
        cvAi?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cinematic_select".
 */
export interface CinematicSelect<T extends boolean = true> {
  avatarModel?: T;
  avatarPortrait?: T;
  heroPoster?: T;
  heroVideoDesktop?:
    | T
    | {
        mp4?: T;
        webm?: T;
      };
  heroVideoMobile?:
    | T
    | {
        mp4?: T;
        webm?: T;
      };
  scrubVideo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}